name: awesome_generator
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  freezed_annotation: ^0.14.3
  github: ^8.1.1
  liquid_engine: ^0.2.2
  pub_api_client: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  pedantic: ^1.10.0
