name: awesome_generator
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  github: ^8.1.1
  liquid_engine: # ^0.2.2
    git:
      url: https://github.com/jpnurmi/liquid_dart.git
      ref: firstof
  path: ^1.8.0
  pub_api_client: ^2.1.0
  stash: ^3.2.2
  stash_file: ^3.2.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1

executables:
  awesome-generator: main
