name: awesome_generator
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  github: ^8.1.1
  pub_api_client: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.10.0
